project_id = "jxfqfrfpaiijyvciclrw"

[functions.get-secret]
verify_jwt = false

[functions.get-usdc-balance]
verify_jwt = false

[functions.secure-profile-operations]
verify_jwt = false

[functions.secure-subscription-operations]
verify_jwt = false

[functions.test-privy-secrets]
verify_jwt = false

[functions.get-gooddollar-balance]
verify_jwt = false

[functions.gooddollar-identity-check]
verify_jwt = false

[functions.gooddollar-claim]
verify_jwt = false

[functions.get-privy-config]
verify_jwt = false

[functions.get-token-balance]
verify_jwt = false

[functions.get-conversion-rate]
verify_jwt = false

[functions.get-mobile-networks]
verify_jwt = false

[functions.create-withdrawal]
verify_jwt = false

[functions.process-mobile-money-transfer]
verify_jwt = false

[functions.payment-callback]
verify_jwt = false

[functions.get-portfolio]
verify_jwt = false