project_id = "jxfqfrfpaiijyvciclrw"

[functions.get-secret]
verify_jwt = false

[functions.get-usdc-balance]
verify_jwt = false

[functions.secure-profile-operations]
verify_jwt = false

[functions.secure-subscription-operations]
verify_jwt = false

[functions.test-privy-secrets]
verify_jwt = false

[functions.get-gooddollar-balance]
verify_jwt = false

[functions.gooddollar-identity-check]
verify_jwt = false

[functions.gooddollar-claim]
verify_jwt = false