project_id = "jxfqfrfpaiijyvciclrw"

[functions.get-secret]
verify_jwt = false

[functions.get-usdc-balance]
verify_jwt = false

[functions.secure-profile-operations]
verify_jwt = true

[functions.secure-subscription-operations]
verify_jwt = true