// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jxfqfrfpaiijyvciclrw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp4ZnFmcmZwYWlpanl2Y2ljbHJ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwODU2NzcsImV4cCI6MjA2NTY2MTY3N30.VyC5_Ib3appTm0MYut0e4_2McGdg0yyJhVTFhRZqRAM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);